spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taobao_2?useSSL=false & serverTimezone=UTC & serverTimezone=GMT%2B8
    username: root
    password: Zx13318082824!

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: final_project_springboot